import { randomBytes, randomUUID } from 'node:crypto';
import { normalizeHttpUrl } from '../domain/identity.js';

export class BrowserBridge {
  constructor({store}){this.store=store;this.tokens=new Map();this.queues=new Map();for(const x of store.getSetting('bridge.pairings',[])){this.tokens.set(x.token,x);this.queues.set(x.key,[]);}}
  pair(browser,profile='Default'){const key=`${browser}:${profile}`;for(const [token,x] of this.tokens){if(x.key===key)this.tokens.delete(token);}const token=randomBytes(24).toString('base64url');const entry={token,browser,profile,key,createdAt:new Date().toISOString()};this.tokens.set(token,entry);if(!this.queues.has(key))this.queues.set(key,[]);this.#persist();return {token,browser,profile,baseUrl:'http://127.0.0.1:8790',version:'0.1.0'};}
  listPairings(){return [...this.tokens.values()].map(({token,...x})=>({...x,tokenHint:`${token.slice(0,4)}…${token.slice(-4)}`}));}
  authenticate(token){return this.tokens.get(token)||null;}
  enqueue(token,command){const session=this.authenticate(token);if(!session)throw new Error('Unknown bridge token');const id=command.id??`cmd_${randomUUID()}`;this.queues.get(session.key).push({...command,id});return id;}
  poll(token){const s=this.authenticate(token);if(!s)return null;return this.queues.get(s.key).shift()??null;}
  captureResult(token,payload){const s=this.authenticate(token);if(!s)throw new Error('Unauthorized bridge');return this.store.capture({source:'bridge',runId:payload.commandId?`bridge_${payload.commandId}`:null,browsers:[{browser:s.browser,profile:s.profile,status:payload.status??'ok',error:payload.error,tabs:payload.tabs??[]}]});}
  requestCapture(token){return this.enqueue(token,{type:'capture'});}
  requestCurrentPage(token,{closeAfterSave=false,note='' }={}){return this.enqueue(token,{type:'save-current',closeAfterSave,note});}
  currentPageResult(token,{tab,note='',closeAfterSave=false,commandId}){const session=this.authenticate(token);if(!session)throw new Error('Unauthorized bridge');const cap=this.store.capture({source:'current-page',runId:commandId?`current_${commandId}`:null,browsers:[{browser:session.browser,profile:session.profile,status:'ok',tabs:[tab]}]});const rid=this.store.findResourceByUrl(tab.url);if(rid&&note?.trim()&&!cap.replayed)this.store.addNote(rid,note,{source:'typed',confirmed:true});let close=null;if(rid&&closeAfterSave){const target={tabId:tab.id,windowId:tab.windowId,url:tab.url};const action=this.store.createBrowserAction({id:commandId?`close_${commandId}`:undefined,actionType:'close',resourceId:rid,target});close={actionId:action.id,target};}return {capture:cap,resourceId:rid,close};}
  requestClose({token,resourceId,target,actionId}){const action=this.store.createBrowserAction({id:actionId,actionType:'close',resourceId,target});if(action.status!=='requested')return action;this.enqueue(token,{id:action.id,type:'close',target});return action;}
  closeResult(token,{actionId,observed}){const s=this.authenticate(token);if(!s)throw new Error('Unauthorized bridge');const action=this.store.getBrowserAction(actionId);if(!action)return null;if(action.status!=='requested')return action;const expected=action.target;let status='refused',reason='Live target did not match saved close request';try{if(observed?.tabId===expected.tabId&&observed?.windowId===expected.windowId&&observed?.url===expected.url){status=observed.closed?'closed':'failed';reason=observed.closed?'Closed after exact live target revalidation':observed.error||'Browser reported close failure';}}catch{}return this.store.finishBrowserAction(actionId,status,{...observed,reason,browser:s.browser,profile:s.profile});}
  #persist(){this.store.setSetting('bridge.pairings',[...this.tokens.values()]);}
}
