from __future__ import annotations

from http import HTTPStatus
from typing import Any, Protocol


class ApiRequest(Protocol):
    workspace_server: Any
    headers: Any
    wfile: Any

    def _idempotency_key(self) -> str: ...

    def _read_empty_body(self) -> None: ...

    def _read_json_body(self) -> dict[str, Any]: ...

    def _read_raw_body(self, maximum: int) -> bytes: ...

    def _send_json(self, value: Any, status: HTTPStatus = HTTPStatus.OK) -> None: ...

    def _serve_audio(self, note_id: str) -> None: ...

    def end_headers(self) -> None: ...

    def send_error(self, code: int | HTTPStatus) -> None: ...

    def send_header(self, keyword: str, value: str) -> None: ...

    def send_response(self, code: int | HTTPStatus) -> None: ...
