"""Stable public API for TabAtlas commands, tests, and integrations."""

from .capture import (
    canonicalize_url,
    classify_url,
    latest_capture_rows,
    normalize_snapshot_document,
    resource_id,
    store_snapshot,
)
from .catalog import (
    annotation_batch,
    apply_annotations,
    current_resources,
    discovery_batch,
    discovery_resources,
    display_url,
    exact_duplicate_summary,
    inventory,
    library_resources,
    query_resources,
    remove_library_resources,
    set_discovery_state,
)
from .common import normalize_browser
from .constants import (
    LEGACY_CAPTURE_PROTOCOL_VERSION,
    LIBRARY_STATES,
    MUTATION_PROTOCOL_VERSION,
    PUBLIC_PREVIEW_USER_AGENT,
    RESOURCE_STATUSES,
    SCHEMA_VERSION,
    SPACE_DEFINITIONS,
    TABATLAS_EXTENSION_ID,
    TABATLAS_EXTENSION_URL_PREFIX,
    TARGET_HASH_PROTOCOL_VERSION,
    TASK_STATUSES,
    TOPIC_PARENT_DEFAULTS,
    TRACKING_PARAMETERS,
)
from .database import (
    SCHEMA,
    connect,
    mark_pairing_seen,
    open_connection,
    pairing_secret,
    pairing_status,
    protocol_proof,
    revoke_pairing,
    save_pairing,
    token_hash,
    utc_now,
)
from .files import copy_extension, import_file
from .mutations import (
    build_archive_cleanup_plan,
    build_archive_plan,
    build_exact_duplicate_plan,
    finalize_archive_plan,
    finalize_mutation_plan,
    record_archive_cleanup_result,
    record_archive_plan,
    record_mutation_plan,
)
from .presentation import (
    generate_report,
    report_collection_summaries,
    report_group_summaries,
    report_payload,
    report_source_summaries,
    resource_presentation,
)
from .previews import cache_public_previews, register_local_preview

__all__ = [
    "LEGACY_CAPTURE_PROTOCOL_VERSION",
    "LIBRARY_STATES",
    "MUTATION_PROTOCOL_VERSION",
    "PUBLIC_PREVIEW_USER_AGENT",
    "RESOURCE_STATUSES",
    "SCHEMA",
    "SCHEMA_VERSION",
    "SPACE_DEFINITIONS",
    "TABATLAS_EXTENSION_ID",
    "TABATLAS_EXTENSION_URL_PREFIX",
    "TARGET_HASH_PROTOCOL_VERSION",
    "TASK_STATUSES",
    "TOPIC_PARENT_DEFAULTS",
    "TRACKING_PARAMETERS",
    "annotation_batch",
    "apply_annotations",
    "build_archive_cleanup_plan",
    "build_archive_plan",
    "build_exact_duplicate_plan",
    "cache_public_previews",
    "canonicalize_url",
    "classify_url",
    "connect",
    "copy_extension",
    "current_resources",
    "discovery_batch",
    "discovery_resources",
    "display_url",
    "exact_duplicate_summary",
    "finalize_archive_plan",
    "finalize_mutation_plan",
    "generate_report",
    "import_file",
    "inventory",
    "latest_capture_rows",
    "library_resources",
    "mark_pairing_seen",
    "normalize_browser",
    "normalize_snapshot_document",
    "open_connection",
    "pairing_secret",
    "pairing_status",
    "protocol_proof",
    "query_resources",
    "record_archive_cleanup_result",
    "record_archive_plan",
    "record_mutation_plan",
    "register_local_preview",
    "remove_library_resources",
    "report_collection_summaries",
    "report_group_summaries",
    "report_payload",
    "report_source_summaries",
    "resource_id",
    "resource_presentation",
    "revoke_pairing",
    "save_pairing",
    "set_discovery_state",
    "store_snapshot",
    "token_hash",
    "utc_now",
]
